### ISSUE TITLE
Not working, is there any library changes?

### ISSUE THREAD

**Issue by Bolofofopt** [PuceBaboon/ESP32_W5500_NTP_CLIENT#1]
I'm currently trying to use your code and it's not working, it says "ethernet shield not found".

Are any library changes that you did?

**Comment by PuceBaboon** [comment]
Hi Bolofofopt,

  Nope!  There haven't been any changes to this project in 5 years  (Wow! has it really been that long?!?!).
  There is no reference in my code to the word "shield", so your error isn't coming directly from the code (but may be coming from the Arduino framework).

  With -any- message suggesting a communications error between the ESP32 and W5500 though, the problem has generally proven to be a cabling issue in the vast majority of cases ...so, first make sure you have a good solid power and ground connection between your ESP32 and W5500 board.  Next, take a known-good jumper cable and use it to replace each of the cables in your inter-wiring, one-by-one (and obviously, power down both boards while you re-make the connections).

  If you're still having problems, please get back with a copy of the actual error message, let us know exactly which ESP32 and W5500 modules you're using and provide a good, clear photo of your set-up.

  Good luck and please let us know how it goes,

**Comment by Bolofofopt** [comment]
Heelo, thanks for the response. Using your example and library code, just copy and paste, it gave a lot of errors so I tried to adapt the code because a lot of funtions and stuff was giving straight up errors, I will try to solve the issue and because of the errors it gave me just with coping the code I will try another library. Thanks a lot for the response and I'm sorry for wasting your time!
